version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-village
    environment:
      POSTGRES_USER: village_user
      POSTGRES_PASSWORD: village_pass
      POSTGRES_DB: smart_village
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
